export const foodCategories=[
    {
        id:1,
        img:require('../assets/food.png'),
        name:"foods"
    },
    {
        id:2,
        img:require('../assets/juice.png'),
        name:"juice"
    },
    {
        id:3,
        img:require('../assets/fruits.png'),
        name:"fruits"
    },
    {
        id:4,
        img:require('../assets/vegetables.jpg'),
        name:"vegetables"
    },
    {
        id:5,
        img:require('../assets/cocktail.png'),
        name:"cocktails"
    },
    {
        id:6,
        img:require('../assets/beer.png'),
        name:"beers"
    },
]

export const recommendedProducts=[
    {
        id:"1",
        img:require('../assets/burger.png'),
        name:"Burger",
        price:5
    },
    {
        id:"2",
        img:require('../assets/pizza.jpg'),
        name:"Pizza",
        price:6
    },
    {
        id:"3",
        img:require('../assets/coffee.png'),
        name:"Coffee",
        price:3
    },
    {
        id:"4",
        img:require('../assets/chicken.jpg'),
        name:"Chicken",
        price:12
    },
    {
        id:"5",
        img:require('../assets/steak.jpg'),
        name:"Steak",
        price:15
    },
]

export const mostPopularProducts=[
    {
        id:"1",
        img:require('../assets/burger.png'),
        name:"Burger"
    },
    {
        id:"2",
        img:require('../assets/chicken.jpg'),
        name:"chicken"
    },
    {
        id:"3",
        img:require('../assets/steak.jpg'),
        name:"Steak"
    },
    {
        id:"4",
        img:require('../assets/burger.png'),
        name:"Burger"
    },
    {
        id:"5",
        img:require('../assets/chicken.jpg'),
        name:"chicken"
    },
    {
        id:"6",
        img:require('../assets/steak.jpg'),
        name:"Steak"
    },
]